spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 80

hardware:
  gpio-platform: pi4j
  modules:
    motor-drivers:
      - driver-name: Feeder
        pins:
          en: 2
          dir: 1
          step: 0
    scales:
      - scales-name: FeederScales
#        calibration-factor: 1123
        calibration-factor: 1119
        timeout-in-millis: 3000
        gain: gain_128
        pins:
          clock: 7
          data: 5
catfeeder:
  average-weight-measures: 3